# Generated by Django 5.2.16 on 2026-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_answeroption_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='Другое', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
