# Generated by Django 5.2.16 on 2026-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quiz_is_published_alter_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='estimated_time',
            field=models.PositiveIntegerField(default=10, help_text='Примерное время прохождения (минуты)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
